countries.codes <- structure(list(country.code = c("All", "AF", "AO", "AG", "AR", 
                             "AW", "AU", "AT", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BO", 
                             "BA", "BW", "BR", "BG", "BF", "KH", "CM", "CA", "CV", "CL", "CO", 
                             "CR", "CI", "HR", "CZ", "DK", "DO", "EC", "EG", "SV", "EE", "FJ", 
                             "FI", "FR", "GA", "GE", "DE", "GH", "GR", "GT", "GW", "HT", "HN", 
                             "HK", "HU", "IN", "ID", "IQ", "IE", "IL", "IT", "JM", "JP", "JO", 
                             "KZ", "KE", "KW", "KG", "LA", "LV", "LB", "LY", "LI", "LT", "LU", 
                             "MY", "ML", "MT", "MU", "MX", "MD", "MN", "MA", "MZ", "MM", "NA", 
                             "NP", "NL", "NZ", "NI", "NE", "NG", "MK", "NO", "OM", "PK", "PA", 
                             "PG", "PY", "PE", "PH", "PL", "PT", "PR", "QA", "RE", "RO", "RU", 
                             "RW", "SA", "SN", "RS", "SG", "SK", "SI", "ZA", "KR", "ES", "LK", 
                             "SE", "CH", "TW", "TJ", "TZ", "TH", "BS", "TG", "TT", "TR", "UG", 
                             "UA", "AE", "GB", "US", "UY", "VE", "VN", "YE", "ZM", "ZW"), 
     country.region = c("All countries/regions", "Afghanistan", "Angola", "Antigua and Barbuda", 
                        "Argentina", "Aruba", "Australia", "Austria", "Bahrain", 
                        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", 
                        "Benin", "Bolivia", "Bosnia and Herzegovina", "Botswana", 
                        "Brazil", "Bulgaria", "Burkina Faso", "Cambodia", "Cameroon", 
                        "Canada", "Cape Verde", "Chile", "Colombia", "Costa Rica", 
                        "Côte d'Ivoire", "Croatia", "Czechia", "Denmark", "Dominican Republic", 
                        "Ecuador", "Egypt", "El Salvador", "Estonia", "Fiji", "Finland", 
                        "France", "Gabon", "Georgia", "Germany", "Ghana", "Greece", 
                        "Guatemala", "Guinea-Bissau", "Haiti", "Honduras", "Hong Kong", 
                        "Hungary", "India", "Indonesia", "Iraq", "Ireland", "Israel", 
                        "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", 
                        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Libya", 
                        "Liechtenstein", "Lithuania", "Luxembourg", "Malaysia", "Mali", 
                        "Malta", "Mauritius", "Mexico", "Moldova", "Mongolia", "Morocco", 
                        "Mozambique", "Myanmar (Burma)", "Namibia", "Nepal", "Netherlands", 
                        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", 
                        "Norway", "Oman", "Pakistan", "Panama", "Papua New Guinea", 
                        "Paraguay", "Peru", "Philippines", "Poland", "Portugal", 
                        "Puerto Rico", "Qatar", "Réunion", "Romania", "Russia", "Rwanda", 
                        "Saudi Arabia", "Senegal", "Serbia", "Singapore", "Slovakia", 
                        "Slovenia", "South Africa", "South Korea", "Spain", "Sri Lanka", 
                        "Sweden", "Switzerland", "Taiwan", "Tajikistan", "Tanzania", 
                        "Thailand", "The Bahamas", "Togo", "Trinidad and Tobago", 
                        "Turkey", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", 
                        "United States", "Uruguay", "Venezuela", "Vietnam", "Yemen", 
                        "Zambia", "Zimbabwe")), class = "data.frame", row.names = c(NA, 
                                                                                    -136L))
